spring.application.name=otobathanh

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.web.resources.static-locations=classpath:/static/

cloudianry.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudianry.api_key=${CLOUDINARY_API_KEY}
cloudianry.api_secret=${CLOUDINARY_API_SECRET}

coze.api.base-url=${COZE_API_BASE_URL}
coze.api.access-token=${COZE_API_ACCESS_TOKEN}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
